stages:          # List of stages for jobs, and their order of execution
  - main


develop:
  image: alpine
  stage: main
  script:
    - apk add --no-cache openssh-client bash
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - bash -c "ssh-add <(echo '$CI_SSH_PRIVATE_KEY')"
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh root@3.137.70.129 'cd /var/www/stage541.yourdesigndemo.net/gabriel && git pull'
  only:
    - main
